# NumPy

In [3]:
import numpy as np

## Массивы в NumPy

- **array(object)** - n-мерный массив из любой (возможно, вложенной) последовательности
- **eye(N, M=N, k=0)** - двумерный массив с N строками с единицами на диагонали и нулями во всех остальных позициях. Число столбцов M по умолчанию равно N, k — сдвиг диагонали (0 для основной диагонали, положительные числа для верхних диагоналей и отрицательные для нижних)
- **zeros(shape)** - новый массив указанной формы, заполненный нулями,
- **ones(shape)** - новый массив указанной формы, заполненный единицами,
- **full(shape, fill_value)** - новый массив указанной формы, заполненный fill_value.

In [4]:
a = np.array([[1,2,3], [4,5,6]])  # создаём массив
print(a)  # смотрим на массив

[[1 2 3]
 [4 5 6]]


In [19]:
print('По умолчанию:\n',np.eye(3))
print('\nИспользуя все параметры:\n',np.eye(3,4,1))

По умолчанию:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Используя все параметры:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [26]:
print(np.ones(3))

[1. 1. 1.]


In [28]:
print(np.full((2,3), 5))

[[5 5 5]
 [5 5 5]]


Форма массива в NumPy хранится в атрибуте **shape**.

In [5]:
a.shape  # смотрим на форму массива из первого примера

(2, 3)