# NumPy

In [6]:
import numpy as np

## Массивы в NumPy

- **array(object)** - n-мерный массив из любой (возможно, вложенной) последовательности
- **eye(N, M=N, k=0)** - двумерный массив с N строками с единицами на диагонали и нулями во всех остальных позициях. Число столбцов M по умолчанию равно N, k — сдвиг диагонали (0 для основной диагонали, положительные числа для верхних диагоналей и отрицательные для нижних)
- **zeros(shape)** - новый массив указанной формы, заполненный нулями,
- **ones(shape)** - новый массив указанной формы, заполненный единицами,
- **full(shape, fill_value)** - новый массив указанной формы, заполненный fill_value.

In [7]:
a = np.array([[1,2,3], [4,5,6]])  # создаём массив
print(a)  # смотрим на массив

[[1 2 3]
 [4 5 6]]


In [8]:
print('По умолчанию:\n',np.eye(3))
print('\nИспользуя все параметры:\n',np.eye(3,4,1))

По умолчанию:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Используя все параметры:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [10]:
print(np.ones(3))

[1. 1. 1.]


In [11]:
print(np.full((2,3), 5))

[[5 5 5]
 [5 5 5]]


Форма массива в NumPy хранится в атрибуте **shape**.

In [12]:
a.shape  # смотрим на форму массива из первого примера

(2, 3)

## Основные методы ndarray

### Форма массива

- **a.flatten()** — превращает массив в одномерный.
- **a.T или a.transpose(axes)** — транспонирование (или смена порядка осей в случае, когда размерность массива больше двух).
- **a.reshape(shape)** — смена формы массива. Массив "распрямляется" и построчно заполняется в новую форму.

In [21]:
import random
w = np.array(random.sample(range(1000), 12)) # одномерный массив из 12 случайных чисел от 1 до 1000
w_resh = w.reshape((2,2,3)) # превратим w в трёхмерную матрицу
print('одномерный массив:\n', w)
print('\nтрёхмерная матрица:\n', w_resh)
print('\nсмена порядка осей:\n', w_resh.transpose(0,2,1))

одномерный массив:
 [ 91 426 111 832 482  30 785 723 889 910  67 622]

трёхмерная матрица:
 [[[ 91 426 111]
  [832 482  30]]

 [[785 723 889]
  [910  67 622]]]

смена порядка осей:
 [[[ 91 832]
  [426 482]
  [111  30]]

 [[785 910]
  [723  67]
  [889 622]]]


### Базовые статистики

- **a.min(axis=None)**, **a.max(axis=None)**, **a.mean(axis=None)**, **a.std(axis=None)** — минимум, максимум, среднее арифметическое и стандартное отклонение вдоль указанной оси. По умолчанию ось не указана и статистика считается по всему массиву. 
- **a.argmin(axis=None)**, **a.argmax(axis=None)** — индексы минимального и максимального элемента.

In [36]:
v = np.array([[1, 2, 3, 4] for i in range(3)])
print(v)
print('\nвдоль столбцов', v.mean(axis = 0))        # вдоль столбцов
print('\nвдоль строк', v.mean(axis=1))             # вдоль строк
print('\nвдоль всего массива', v.mean(axis=None))  # вдоль всего массива

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

вдоль столбцов [1. 2. 3. 4.]

вдоль строк [2.5 2.5 2.5]

вдоль всего массива 2.5


- **a.sum(axis=None)**, **a.prod(axis=None)** - сумма и произведение всех элементов вдоль указанной оси.
- **a.cumsum(axis=None)**, **a.cumprod(axis=None)** - частичные суммы и произведения (для 


In [44]:
print('\nсумма вдоль столбцов', v.sum(axis = 0)) 
print('\n частичные суммы вдоль столбцов\n', v.cumsum(axis = 0)) 


сумма вдоль столбцов [ 3  6  9 12]

 частичные суммы вдоль столбцов
 [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]


### Линейная алгебра

Пакет **numpy.linalg** содержит большую часть стандартных операций и разложений матриц.
- **a.dot(b)** — матричное произведение двух массивов (размерности должны быть согласованы),
- **linalg.matrix_power(M, n)** — возведение матрицы M в степень n,
- **a.T** — транспонирование
- **linalg.norm(a, ord=None)** — норма матрицы a, по умолчанию норма Фробениуса для матриц и L2-норма для векторов; подробное описание возможных норм — в справке,
- **linalg.inv(a)** — матрица, обратная к a (если a необратима, выбрасывается LinAlgError; псевдообратная считается через linalg.pinv(a))

In [55]:
w = np.array([1, 2, 3])
a = w.dot([1,2,3])
print(a)

# ainv = np.linalg.inv(a)
# print(a.dot(ainv))

14


----------------------------------------------------------------------------------------------

# Практика

### Задача 1
Создайте и напечатайте (с помощью функции print) массив класса np.ndarray ширины 4 и высоты 3 с двойками на главной диагонали и единицами на первой диагонали над главной, т.е. воплощение матрицы

In [14]:
ar = np.eye(3,4,1) + np.eye(3, 4)*2
print(ar)

[[2. 1. 0. 0.]
 [0. 2. 1. 0.]
 [0. 0. 2. 1.]]


### Задача 2
Создайте массив mat из рандомных чисел. Превратите его в вертикальный вектор и напечатайте.

In [28]:
mat = np.array(random.sample(range(100), 10))
print(mat.reshape(10,1))

[[64]
 [33]
 [85]
 [15]
 [46]
 [47]
 [10]
 [74]
 [48]
 [26]]
