# PyTorch

## Импорт библиотек

In [2]:
import torch
print(torch.cuda.is_available())

True


## Тензор

### Создание Тензора

In [3]:
torch.tensor([2,3]) 

tensor([2, 3])

In [3]:
# тензор двумерного массива с объявлением типа данных
torch.tensor([[2,3], [4,5]], dtype=torch.int32)

tensor([[2, 3],
        [4, 5]], dtype=torch.int32)

In [4]:
# тензор двумерного массива с объявлением типа данных FLOAT (важно, если requires_grad=True)
# requires_grad=True - для этого тензора будут вычисляться градиенты во всех функциях, где он будет участвовать
torch.tensor([[2,3], [4,5]], dtype=torch.float32, requires_grad=True)

tensor([[2., 3.],
        [4., 5.]], requires_grad=True)

In [7]:
# создание и перемещение тензора на графический процессор
torch.tensor([[2,3],[4,5]], device=torch.device('cuda:0'))

tensor([[2, 3],
        [4, 5]], device='cuda:0')


### Основные свойства и методы Тензора

In [26]:
tensor = torch.tensor([[[2,3], [4,5]], [[6,7], [8,9]]], dtype=torch.float32, requires_grad=True)

In [27]:
tensor

tensor([[[2., 3.],
         [4., 5.]],

        [[6., 7.],
         [8., 9.]]], requires_grad=True)

In [32]:
#тип переменных

tensor.dtype

torch.float32

In [33]:
# размер тензора

print(tensor.shape)
print(tensor.size())

torch.Size([2, 2, 2])
torch.Size([2, 2, 2])


In [34]:
# количество осей в тензоре

tensor.ndim

3

In [35]:
# обращение к элементу тензора (это тоже не число, а тензор)

tensor[0,0,0]

tensor(2., grad_fn=<SelectBackward0>)

In [36]:
type(tensor[0,0,0])

torch.Tensor

In [37]:
#получение непосредственно числа (из элемента тензора)

tensor[0,0,0].item()

2.0

In [38]:
type(tensor[0,0,0].item())

float

### Создание Тензоров разного размера

In [40]:
#матрица со всеми нулями заданной размерности

tensor = torch.zeros([2,3,2])
tensor

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [42]:
#матрица со всеми единицами заданной размерности

tensor = torch.ones([2,3,2], dtype=torch.int32)
tensor

tensor([[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]]], dtype=torch.int32)

In [44]:
#матрица со всеми нулями и размерностью аналогично той матрице, что предана в метод

tensor = torch.zeros_like(tensor)
tensor

tensor([[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]], dtype=torch.int32)

In [47]:
# матрица размерностью аналогично той, что предана в метод, но заполнена переданным элементом

tensor = torch.full_like(tensor, 7)
tensor

tensor([[[7, 7],
         [7, 7],
         [7, 7]],

        [[7, 7],
         [7, 7],
         [7, 7]]], dtype=torch.int32)

In [49]:
#тензор со значениями заданного диапазона и с указанным шагом

torch.arange(2, 10, 0.5)

tensor([2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000, 5.5000, 6.0000,
        6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000])

In [55]:
# диагональная матрица

torch.diag(torch.tensor([3,2]))

tensor([[3, 0],
        [0, 2]])

In [56]:
# единичная матрица

torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [60]:
# нижняя треугольная матрица

torch.tril(torch.tensor([[1,2,3],[2,3,4],[3,4,5]]))

tensor([[1, 0, 0],
        [2, 3, 0],
        [3, 4, 5]])

### Изменение размера, создание дополнительных осей

In [77]:
tensor = torch.tensor([1,2,3,4])
tensor

tensor([1, 2, 3, 4])

In [78]:
# Изменение размера тензора

tensor_1 = tensor.view([4,1])
tensor_2 = tensor.reshape([2,2])

print(tensor_1, '\n\n', tensor_2)

tensor([[1],
        [2],
        [3],
        [4]]) 

 tensor([[1, 2],
        [3, 4]])


In [79]:
# Добавление осей

print(tensor, tensor.shape) # до добавления оси

tensor = torch.unsqueeze(tensor, 0) # добавление оси

print(tensor, tensor.shape) # после добавления оси

tensor([1, 2, 3, 4]) torch.Size([4])
tensor([[1, 2, 3, 4]]) torch.Size([1, 4])


### Арифметические операции и мат. функции

In [82]:
# Арифметические операции

tensor = torch.tensor([1,2,3,4,5])

tensor_prod = tensor * 5
tensor_sum = tensor + torch.tensor([1,2,3,4,5])

#!!!! ТАК ДЕЛАТЬ НЕЛЬЗЯ - ТЕНЗОР СО СПИСКОМ НЕ СКЛАДЫВАЮТ. !!!!#
#          tensor_sum = tensor + [1,2,3,4,5]

print(tensor_prod, tensor_sum, sep='\n\n')

tensor([ 5, 10, 15, 20, 25])

tensor([ 2,  4,  6,  8, 10])


In [84]:
# Математические функции

tensor = torch.tensor([1,2,3,4,5,6], dtype = torch.float32)

print('Sum: ', tensor.sum())
print('Mean: ', tensor.mean())

Sum:  tensor(21.)
Mean:  tensor(3.5000)


In [168]:
# Математические функции по осям тензора

tensor = torch.tensor([1,2,3,4,5,6], dtype = torch.float32)
tensor = tensor.view([2,3]) #изменим размерность тензора, чтобы было видно, что измерение происходит по осям

tensor_mean = tensor.mean(dim=1,
                          #keepdim=True
                         )

#keepdim=True - ось, по котрой считается среднее значение НЕ УДАЛЯЕТСЯ
tensor_mean_keepdim = tensor.mean(dim=1,
                          keepdim=True
                         )

print('Transformed Tensor: \n', f'\033[94m{tensor}\033[0m', '\n')
print('Tensor with means by axes:', f'\033[94m{tensor_mean}\033[0m', '\n')
print('Shape of tensor with means by axes: ', f'\033[94m{tensor_mean.shape}\033[0m', '\n')
print('\033[91mWith keepdim:\033[0m')
print('Tensor with means by axes:\n', f'\033[94m{tensor_mean_keepdim}\033[0m', '\n')
print('Shape of tensor with means by axes: ', f'\033[94m{tensor_mean_keepdim.shape}\033[0m', '\n')

Transformed Tensor: 
 tensor([[1., 2., 3.],
        [4., 5., 6.]]) 

Tensor with means by axes: tensor([2., 5.]) 

Shape of tensor with means by axes:  torch.Size([2]) 

With keepdim:
Tensor with means by axes:
 tensor([[2.],
        [5.]]) 

Shape of tensor with means by axes:  torch.Size([2, 1]) 



### Перевод Тензора на GPU или CPU

In [142]:
#доступность центрального процессора
print(torch.cpu.is_available())

#доступность графического процессора
print(torch.cuda.is_available())

True
True


##### По умолчанию все тензоры создаются на CPU

In [154]:
tensor = torch.tensor([1.,2.,3.], requires_grad=True) 
# requires_grad=True - PyTorch запоминает всё, что с происходит с тензором, чтобы потом автоматически рассчитать производные (градиенты)

In [157]:
#Способы перевести тензор на CPU (переносится копия)

tensor_1 = tensor.cpu()
print(tensor_1)
tensor_2 = tensor.to('cpu')
print(tensor_2)

tensor([1., 2., 3.], requires_grad=True)
tensor([1., 2., 3.], requires_grad=True)


In [159]:
#Способы перевести тензор на GPU (переносится копия)

tensor_3 = tensor.cuda()
print(tensor_3)
tensor_4 = tensor.to('cuda')
print(tensor_4)

tensor([1., 2., 3.], device='cuda:0', grad_fn=<ToCopyBackward0>)
tensor([1., 2., 3.], device='cuda:0', grad_fn=<ToCopyBackward0>)


##### Безопасный способ перевода тензора на GPU

In [161]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor = tensor.to(device)
tensor.device

device(type='cuda', index=0)

<div class="alert alert-block alert-danger"> Нельзя делать совместные операции, если один тензор на GPU, а другой на CPU  </div>

##### Перенос тензора на CPU

In [165]:
new_tensor_1 = tensor_3.cpu()
new_tensor_1

tensor([1., 2., 3.], grad_fn=<ToCopyBackward0>)

##### Перенос тензора на CPU c откреплением графа вычислений градиента этого тензора

In [167]:
new_tensor_2 = tensor_3.cpu().detach()
new_tensor_2

tensor([1., 2., 3.])

## Обучение классификатора

### Создание датасета